//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public System.Guid CategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
