//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.ContactDetails = new HashSet<ContactDetail>();
        }
    
        public System.Guid ContactId { get; set; }
        public System.Guid CategoryId { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public Nullable<System.Guid> StateId { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public string ContactName { get; set; }
        public string ContactDescription { get; set; }
        public string Icon { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<ContactDetail> ContactDetails { get; set; }
    }
}
