//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactType
    {
        public ContactType()
        {
            this.ContactDetails = new HashSet<ContactDetail>();
        }
    
        public System.Guid ContactTypeId { get; set; }
        public string ContactTypeName { get; set; }
        public Nullable<byte> Sequence { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<ContactDetail> ContactDetails { get; set; }
    }
}
