//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Cities = new HashSet<City>();
            this.Contacts = new HashSet<Contact>();
        }
    
        public System.Guid StateId { get; set; }
        public System.Guid CountryId { get; set; }
        public string StateName { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual Country Country { get; set; }
    }
}
